### ISSUE TITLE
KeyError: 'original_path'

### ISSUE THREAD

**Issue by mangopipeline** [rtfd/sphinx-autoapi#158] opened 2019-01-19 04:23 UTC
I'm getting this error when running a make with autoapi configured....
autoapi gets to the "Mapping Data" step so it read 100% of the files...

not sure what i'm missing, it's my first time using this extension so maybe i'm missing something?

Exception occurred:
  File "c:\users\carlos\appdata\local\temp\mango_sphynx\python\lib\site-packages\autoapi\mappers\python.py", line 110, in _resolve_placeholders
    original = all_data[original['original_path']]
KeyError: 'original_path'

to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

Here's what i added to my config....
# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [# 'sphinx.ext.autodoc',
              # 'sphinx.ext.doctest',
              # 'sphinx.ext.mathjax',
              # 'sphinx.ext.napoleon',
              'autoapi.extension']

autoapi_type = 'python'
autoapi_dirs = [r"C:\_PIPELINE\_LIB\PythonLibraries"]
autoapi_keep_files = True

# Add any paths that contain templates here, relative to this directory.

full stack trace attached....
[sphinx-err-f8z4k8.log](https://github.com/rtfd/sphinx-autoapi/files/2775149/sphinx-err-f8z4k8.log)

Advice welcomed :(

**Comment by AWhetter** [comment] 2019-01-19 20:15
This is a duplicate of #156. Wildcard imports that import from another module doing a wildcard import are causing a KeyError.

**Closed by AWhetter** 2019-01-19 20:15 UTC
