### ISSUE TITLE
Ensure correct path name on objects

### ISSUE THREAD

**Issue by agjohnson** [rtfd/sphinx-autoapi#109] opened 2017-04-08 00:43 UTC
There is some edge case that is not accounted for that causes modules to lose the closest parent name from their full qualified name. For instance, I noticed this with the `sphinx.websupport.storage` module, which somehow creates a `sphinx.storage` object. I also noticed this with Django, so it may be fairly common.

**Comment by AWhetter** [comment] 2019-02-28 04:37
autoapi has changed a lot since this was opened and I'm not able to reproduce, so I'm going to close this and assume it has been fixed.

**Closed by AWhetter** 2019-02-28 04:37 UTC
Labels: Language: Python
